### ISSUE TITLE
Create a custom dataset from simulation

### ISSUE THREAD

**Issue by hoangcuongbk80** [pyni/PointNet-_Grasping_Data_Part#2]
Hi,

I'd like to create a grasp dataset for my own objects. Which tool did you used for data generation? Could you describe step by step how to build a custom grasp dataset as you did?

Thanks!

**Comment by pyni** [comment]
We refer dexnet(https://berkeleyautomation.github.io/dex-net/) and openrave (http://www.openrave.org/).  
My paper has presented all the steps to build a custom grasp dataset. The data generation process is offline, so most of our algorithms apply exhaustive search. Usually, for each object (stl file), it spends about 2~3h to generate 300 grasping samples.

**Comment by hoangcuongbk80** [comment]
Thank you! I am working on it.
