### ISSUE TITLE
Could you send your dataset to my email?

### ISSUE THREAD

**Issue by MinchangSung0223** [pyni/PointNet-_Grasping_Data_Part#3]
I am a Korean student. 
Thank you for your research
I want to download your dataset. 
But Baidu 'sign up' is difficult in Korea. 
Could you send your dataset to my email?

email : tjdalsckd@gmail.com

**Comment by trungpham2606** [comment]
@tjdalsckd 
Hello, did you get the dataset ?
If yes, can you send it to my email: trungpham2606@gmail.com
Thanks in advance.
